### ISSUE TITLE
Multiple URLs / TLDs for the same login/password pair

### ISSUE THREAD

**Issue by aubertc** [passff/passff-host#45] opened 2019-08-01 14:34 UTC
### General information. Describe your environment

- Versions
  - Operating system: Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux
  - Browser: Firefox Quantum 60.8.0esr (64-bit)
  - PassFF: 1.9
  - Host app: Installed and working

---

Multiple websites can use the same credentials and yet have different TLDs: the example that comes to mind are https://stackoverflow.com/ , https://serverfault.com/, https://askubuntu.com/, … It is possible to use the same credential on all of them, and yet their URLs have nothing in common.

What should be the way to store the password for those websites?

I tried:

- Example 1

```
password
login: <mylogin>
url: stackoverflow.com, serverfault.com, askubuntu.com
```

- Example 2

```
password
login: <mylogin>
url: stackoverflow.com
url: serverfault.com
url: askubuntu.com
```

- Example 3

```
password
login: <mylogin>
url: stackoverflow.com; serverfault.com; askubuntu.com
```

But none of them works properly, i.e., PassFF always says "No entries matching this url".

**Comment by tuxor1337** [comment] 2019-08-01 15:57
Closing as duplicate of https://github.com/passff/passff/issues/300

**Closed by tuxor1337** 2019-08-01 15:57 UTC

**Comment by aubertc** [comment] 2019-08-02 00:53
> Note that, by default, PassFF does not match the URL contained in the pass entry (because that would require decryption of all entries in the store), but it matches the name of the pass entry.

Ok, thanks, so the "url" field is purely ornamental, from that point of view.

> Closing as duplicate of passff/passff#300

I'm sorry, but I can't get it to work.

It seems to me that I'm following the instructions, but PassFF still gives me "No entries matching this url". Assume that I have:

> Password Store
> └── QA
>      ├── askubuntu
>            └── stackexchange

with `QA/stackexchange` being

    <password>
    login: <login>

and `QA/askubuntu` being

    -> /QA/stackexchange
    login: -> /QA/stackexchange

What am I doing wrong?

**Comment by tuxor1337** [comment] 2019-08-02 05:59
Note that passff/passff#300 is not resolved yet. The feature discussed there is only a draft, and hasn't been implemented yet.

**Comment by aubertc** [comment] 2019-08-02 13:51
Ok, thanks a lot. I did not realized you were discussing a draft implementation.

In the meantime, I can solve my issue relatively easily generating my password store `QA/stackexchange `, and then doing

```
$ cd ~/.password-store/QA
$ ln -s stackexchange.gpg askubuntu.gpg
$ pass git add askubuntu.gpg 
$ ln -s stackexchange.gpg serverfault.gpg
$ pass git add serverfault.gpg 

```
etc.

**Comment by tuxor1337** [comment] 2019-08-02 14:49
Thanks for sharing your workaround :)
